site_name: UrMoAC
site_url: https://github.com/DLR-VF/UrMoAC/
site_description: Urban Mobility Accessibility Calculator
site_author: DLR/VF
docs_dir: ./docs

repo_url: https://github.com/DLR-VF/UrMoAC.git
edit_uri: ""



theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
    palette:
        primary: light green
        
nav:
    - Home: index.md
    - Installation: Installation.md
    - Basic Usage: Usage.md
    - Options: Options.md
    - Input Data Formats: 
        - Origins and Destinations: input_formats/OriginsDestinations.md
        - Road Network: input_formats/RoadNetwork.md
        - Aggregation Areas: input_formats/AggregationAreas.md
        - GTFS Definitions: input_formats/GTFSDefinitions.md
        - Speed Time Lines: input_formats/SpeedTimeLines.md
        - Entrainment Definitions: input_formats/EntrainmentDefinitions.md
        - O/D Connections: input_formats/ODConnections.md
    - Import Scripts: 
        - OpenStreetMap: importer/OpenStreetMap.md
        - GTFS: importer/GTFS.md
        - Shapefiles: importer/Shapefiles.md
    - Output Formats: 
        - Overview: outputs/Overview.md
        - O/D Output: outputs/ODOutput.md
        - Extended O/D Output: outputs/ExtendedODOutput.md
        - Direct Output: outputs/DirectOutput.md
        - O/D Mapping Output: outputs/MappingOutput.md
        - Edge Use Output: outputs/EdgeUseOutput.md
        - Public Transport Output: outputs/PTOutput.md
        - Interchanges Output: outputs/InterchangesOutput.md
        - O/D Output Statistics: outputs/ODStatisticsOutput.md
    - Visualisation Tools: 
        - plot_area.py: eval/PlotArea.md
    - Tutorials: 
        - Overview: tutorials/Overview.md
        - Computing the accessibility to the next public transport halt: tutorials/TutorialNextPTHalt.md
        - Using QGIS to visualise UrMoAC results: tutorials/TutorialQGISVisualisation.md
    - FAQ: FAQ.md
    - ChangeLog: ChangeLog.md
    - Links: Links.md
    - Publications: Publications.md
    - Included Data: IncludedData.md
    - Included Scripts: IncludedScripts.md
    - Developer Docs: 
        - Overview: DeveloperDocs.md
        - Testing UrMoAC: DeveloperTests.md
        - Building a Static Documentation: DeveloperStaticDocumentation.md
        - How To Release: DeveloperHowToRelease.md
    - Legal: 
        - Main: Legal.md
        - License (EPL v2.0): LICENSE.md
        - Disclaimer: Disclaimer.md
        - Impressum: Impressum.md


extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - admonition
    - sane_lists
    - mdx_math
  
copyright: "&copy; Copyright 2016&ndash;2025 German Aerospace Center, Institute of Transport Research, all rights reserved."

use_directory_urls: false

plugins:
    - search